version: '3.8'

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-router
    ports:
      - "4000:4000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - LITELLM_CONFIG_PATH=/app/config/litellm.yaml
      - LITELLM_LOG_PATH=/app/logs
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - litellm-network

  redis:
    image: redis:7-alpine
    container_name: litellm-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-changeme}
    restart: unless-stopped
    networks:
      - litellm-network

  postgres:
    image: postgres:15-alpine
    container_name: litellm-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=litellm
      - POSTGRES_PASSWORD=${DB_PASSWORD:-changeme}
      - POSTGRES_DB=litellm
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - litellm-network

  # Optional: Monitoring with Langfuse
  langfuse:
    image: langfuse/langfuse:latest
    container_name: litellm-monitoring
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://litellm:${DB_PASSWORD:-changeme}@postgres:5432/langfuse
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-changeme}
      - SALT=${SALT:-changeme}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - litellm-network

volumes:
  redis-data:
  postgres-data:

networks:
  litellm-network:
    driver: bridge
