name: Notify Repositories of Documentation Updates

on:
  push:
    branches: [main]
    paths:
      - 'integration-guides/**'
      - 'implementation-guides/**'  
      - 'shared-protocols/**'
      - 'integration-examples/**'
      - 'claude-templates/**'
      - 'setup.sh'
      - 'README.md'
      - 'CONTRIBUTING.md'

jobs:
  analyze-changes:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
      changed-files: ${{ steps.changes.outputs.changed-files }}
      commit-message: ${{ steps.changes.outputs.commit-message }}
      commit-sha: ${{ steps.changes.outputs.commit-sha }}
      frontend-changes: ${{ steps.changes.outputs.frontend-changes }}
      backend-changes: ${{ steps.changes.outputs.backend-changes }}
      integration-changes: ${{ steps.changes.outputs.integration-changes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Analyze changes
        id: changes
        run: |
          # Get changed files
          changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ',' | sed 's/,$//')
          echo "changed-files=$changed_files" >> $GITHUB_OUTPUT
          
          # Get commit info
          commit_message=$(git log -1 --pretty=%s)
          commit_sha=$(git rev-parse --short HEAD)
          echo "commit-message=$commit_message" >> $GITHUB_OUTPUT
          echo "commit-sha=$commit_sha" >> $GITHUB_OUTPUT
          
          # Check if we have relevant changes
          if [ -n "$changed_files" ]; then
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            echo "has-changes=false" >> $GITHUB_OUTPUT
          fi
          
          # Analyze change types
          frontend_files="shared-protocols/general-frontend-integration.md|integration-examples/frontend-integration/|claude-templates/"
          backend_files="implementation-guides/cross-app-authentication/|integration-guides/hi-events/api-requirements.md"
          integration_files="integration-guides/hi-events/|setup.sh"
          
          echo "frontend-changes=false" >> $GITHUB_OUTPUT
          echo "backend-changes=false" >> $GITHUB_OUTPUT  
          echo "integration-changes=false" >> $GITHUB_OUTPUT
          
          echo "$changed_files" | tr ',' '\n' | while read file; do
            if echo "$file" | grep -E "$frontend_files" > /dev/null; then
              echo "frontend-changes=true" >> $GITHUB_OUTPUT
            fi
            if echo "$file" | grep -E "$backend_files" > /dev/null; then
              echo "backend-changes=true" >> $GITHUB_OUTPUT
            fi
            if echo "$file" | grep -E "$integration_files" > /dev/null; then
              echo "integration-changes=true" >> $GITHUB_OUTPUT
            fi
          done

  notify-repositories:
    needs: analyze-changes
    if: needs.analyze-changes.outputs.has-changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: 
          - { name: "tuvens/eventdigest-ai", type: "frontend" }
          - { name: "tuvens/tuvens-client", type: "frontend" }
          - { name: "tuvens/tuvens-api", type: "backend" }
          - { name: "tuvens/hi.events", type: "integration" }
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate repository-specific notification
        id: notification
        run: |
          repo_name="${{ matrix.repo.name }}"
          repo_type="${{ matrix.repo.type }}"
          changed_files="${{ needs.analyze-changes.outputs.changed-files }}"
          commit_message="${{ needs.analyze-changes.outputs.commit-message }}"
          commit_sha="${{ needs.analyze-changes.outputs.commit-sha }}"
          
          # Generate issue title
          title="📢 URGENT: Documentation Updates Available (${commit_sha})"
          
          # Read the appropriate template
          if [ "$repo_type" = "frontend" ]; then
            template_file=".github/templates/frontend-notification.md"
          elif [ "$repo_type" = "backend" ]; then
            template_file=".github/templates/backend-notification.md"
          else
            template_file=".github/templates/integration-notification.md"
          fi
          
          # Replace placeholders in template
          issue_body=$(cat "$template_file")
          issue_body="${issue_body//\[CHANGED_FILES\]/$changed_files}"
          issue_body="${issue_body//\[COMMIT_SHA\]/$commit_sha}"
          issue_body="${issue_body//\[COMMIT_MESSAGE\]/$commit_message}"
          issue_body="${issue_body//\[REPO_NAME\]/$repo_name}"
          
          # Save to file for gh command
          echo "$issue_body" > notification.md
          echo "title=$title" >> $GITHUB_OUTPUT

      - name: Create notification issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if similar issue already exists (within last 24 hours)
          existing_issue=$(gh issue list --repo "${{ matrix.repo.name }}" \
            --search "📢 URGENT: Documentation Updates Available in:title is:open" \
            --json number,createdAt --jq '.[0].number // empty')
          
          if [ -z "$existing_issue" ]; then
            echo "Creating new notification issue in ${{ matrix.repo.name }}"
            gh issue create \
              --repo "${{ matrix.repo.name }}" \
              --title "${{ steps.notification.outputs.title }}" \
              --body-file notification.md \
              --label "documentation,urgent,tuvens-docs-update"
          else
            echo "Recent notification issue already exists (#$existing_issue), skipping"
          fi

  create-tracking-issue:
    needs: [analyze-changes, notify-repositories]
    if: needs.analyze-changes.outputs.has-changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create tracking issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_sha="${{ needs.analyze-changes.outputs.commit-sha }}"
          commit_message="${{ needs.analyze-changes.outputs.commit-message }}"
          changed_files="${{ needs.analyze-changes.outputs.changed-files }}"
          
          # Create tracking issue in tuvens-docs
          gh issue create \
            --title "🔄 Documentation Update Tracking (${commit_sha})" \
            --body "## Documentation Update Distribution Tracking

**Commit**: ${commit_sha}
**Message**: ${commit_message}
**Changed Files**: ${changed_files}

### Repository Notification Status
- [ ] tuvens/eventdigest-ai - Issue created
- [ ] tuvens/tuvens-client - Issue created  
- [ ] tuvens/tuvens-api - Issue created
- [ ] tuvens/hi.events - Issue created

### Integration Status
This issue will be updated as repositories confirm integration of the documentation updates.

**Expected Timeline**: All repositories should integrate within 1 week.

---
*This tracking issue is automatically created when documentation updates are pushed to main.*" \
            --label "tracking,documentation,automation"