#!/bin/bash

# Create Vibe Coder Agent Window with Clear Instructions

osascript <<'END'
tell application "iTerm2"
    create window with default profile
    tell current session of current window
        set name to "🎨 Vibe Coder - Agent Workflows"
        write text "cd /Users/ciarancarroll/code/tuvens/worktrees/tuvens-docs/vibe-coder/feature-agent-workflow-instructions"
        write text "clear"
        write text "echo '╔══════════════════════════════════════════════════════════════╗'"
        write text "echo '║          VIBE CODER AGENT - WORKFLOW INSTRUCTIONS            ║'"
        write text "echo '╚══════════════════════════════════════════════════════════════╝'"
        write text "echo ''"
        write text "echo '📍 Working Directory:'"
        write text "pwd"
        write text "echo ''"
        write text "echo '🌿 Git Branch:'"
        write text "git branch --show-current"
        write text "echo ''"
        write text "echo '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'"
        write text "echo '📋 QUICK START INSTRUCTIONS:'"
        write text "echo '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━'"
        write text "echo ''"
        write text "echo '1. Type: claude'"
        write text "echo ''"
        write text "echo '2. Copy and paste this ENTIRE prompt into Claude:'"
        write text "echo ''"
        write text "echo '════════════════════════════════════════════════════════════════'"
        write text "cat << 'PROMPT'"
        write text "I am the Vibe Coder - experimental agent for creative system building."
        write text ""
        write text "Context Loading:"
        write text "- Load: /Users/ciarancarroll/code/tuvens/tuvens-docs/agentic-development/agent-system/vibe-coder-spec.md"
        write text "- Load: /Users/ciarancarroll/code/tuvens/tuvens-docs/agentic-development/agent-system/agent-identities.md"
        write text "- Load: /Users/ciarancarroll/code/tuvens/tuvens-docs/agentic-development/workflows/orchestrator-agent-workflow.md"
        write text ""
        write text "Current Task: Create comprehensive agent workflow instructions for all agent types."
        write text ""
        write text "Specific Goals:"
        write text "1. Create individual workflow files for each agent type:"
        write text "   - frontend-developer-workflow.md"
        write text "   - backend-developer-workflow.md"
        write text "   - integration-specialist-workflow.md"
        write text "   - vibe-coder-workflow.md"
        write text ""
        write text "2. Each workflow should follow the 6-step pattern from orchestrator-agent-workflow.md"
        write text "3. Include practical examples, specific commands, and clear success criteria"
        write text "4. Update pending-commits with progress and findings"
        write text ""
        write text "Working Directory: /Users/ciarancarroll/code/tuvens/worktrees/tuvens-docs/vibe-coder/feature-agent-workflow-instructions"
        write text "Branch: vibe-coder/feature-agent-workflow-instructions"
        write text ""
        write text "Start by loading the context files above and then begin creating the workflow instructions."
        write text "PROMPT"
        write text "echo '════════════════════════════════════════════════════════════════'"
        write text "echo ''"
        write text "echo '🎯 Mission: Create workflow docs for all 4 agent types'"
        write text "echo '📝 Use the 6-step orchestrator pattern as your template'"
        write text "echo '💾 Remember to update pending-commits/'"
        write text "echo ''"
        write text "echo 'Ready? Type: claude'"
        write text "echo ''"
    end tell
end tell
END