name: Branch Lifecycle - Deleted
on:
  delete:

jobs:
  notify-deletion:
    if: ${{ github.event.ref_type == 'branch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch info
        id: branch_info
        run: |
          echo "branch=${{ github.event.ref }}" >> $GITHUB_OUTPUT
          echo "repo=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT
          echo "author=${GITHUB_ACTOR}" >> $GITHUB_OUTPUT

      - name: Update central tracking
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: branch-deleted
          client-payload: |
            {
              "repository": "${{ steps.branch_info.outputs.repo }}",
              "branch": "${{ steps.branch_info.outputs.branch }}",
              "deletedBy": "${{ steps.branch_info.outputs.author }}",
              "deletedAt": "${{ github.event.repository.updated_at }}"
            }