name: Qodo Review Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  trigger-qodo-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Check if Qodo review already requested
        id: check-existing
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TUVENS_DOCS_TOKEN }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            
            const qodoComments = comments.filter(comment => 
              comment.body.includes('@CodiumAI-Agent /review') && 
              comment.user.type === 'Bot'
            );
            
            console.log(`Found ${qodoComments.length} existing Qodo review comments`);
            return qodoComments.length > 0;

      - name: Request Qodo code review
        if: steps.check-existing.outputs.result == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TUVENS_DOCS_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@CodiumAI-Agent /review'
            });
            
            console.log('✅ Qodo review requested for PR #' + context.issue.number);

      - name: Log automation results
        run: |
          echo "🤖 Qodo Review Automation Results:"
          echo "   - PR Number: ${{ github.event.number }}"
          echo "   - Event Type: ${{ github.event_name }}"
          echo "   - Review Already Requested: ${{ steps.check-existing.outputs.result }}"
          echo "   - New Review Triggered: ${{ steps.check-existing.outputs.result == 'false' }}"