name: Vibe Coder Maintenance Check

on:
  workflow_dispatch:  # Allow manual triggering for testing
  push:
    branches: [ dev ]  # Production workflow triggers only on dev branch
    paths: 
      - 'agentic-development/**'
      - '.claude/**'

jobs:
  create-maintenance-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get current date
      id: date
      run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Check if maintenance issue already exists today
      id: check-issue
      run: |
        # Check if an issue with today's date already exists
        EXISTING_ISSUE=$(gh issue list --search "[Vibe Coder] System Maintenance Check - ${{ steps.date.outputs.current_date }}" --json number --jq '.[0].number // empty')
        if [ -n "$EXISTING_ISSUE" ]; then
          echo "issue_exists=true" >> $GITHUB_OUTPUT
          echo "issue_number=$EXISTING_ISSUE" >> $GITHUB_OUTPUT
        else
          echo "issue_exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.TUVENS_DOCS_TOKEN }}

    - name: Comment on existing maintenance issue
      if: steps.check-issue.outputs.issue_exists == 'true'
      run: |
        gh issue comment ${{ steps.check-issue.outputs.issue_number }} --body "🔄 **Additional Maintenance Trigger**

        **Trigger**: Push to ${{ github.ref_name }} branch affecting agentic-development structure  
        **Commit**: ${{ github.sha }}  
        **Time**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')

        This automated trigger indicates more changes to the agentic-development system that may require maintenance attention."
      env:
        GITHUB_TOKEN: ${{ secrets.TUVENS_DOCS_TOKEN }}

    - name: Create maintenance issue
      if: steps.check-issue.outputs.issue_exists == 'false'
      run: |
        gh issue create \
          --title "[Vibe Coder] System Maintenance Check - ${{ steps.date.outputs.current_date }}" \
          --body "$(cat <<'EOF'
        ## Automated System Maintenance Check
        
        **Agent**: Vibe Coder  
        **Trigger**: Push to develop branch affecting agentic-development structure
        **Date**: ${{ steps.date.outputs.current_date }}
        
        ## Tasks to Complete
        
        ### Documentation Accuracy
        - [ ] Verify `agentic-development/README.md` structure matches actual files
        - [ ] Check file counts are accurate (currently 24 production files)
        - [ ] Validate all load paths in `desktop-project-instructions/README.md`
        - [ ] Ensure agent identity files in `.claude/agents/` are current
        
        ### Reference Integrity  
        - [ ] Check for orphaned files without breadcrumb trails
        - [ ] Verify all cross-references between files work
        - [ ] Test `/start-session` command with each agent
        - [ ] Validate setup scripts work correctly
        
        ### System Hygiene
        - [ ] Move any new design docs to `.temp/` directory
        - [ ] Archive outdated workflow files
        - [ ] Update agent terminal prompts if needed
        - [ ] Check for duplicate instructions between Desktop/Code
        
        ### Integration Testing
        - [ ] Test Desktop → Code handoff flow
        - [ ] Verify worktree organization works
        - [ ] Check GitHub issue creation via MCP
        - [ ] Validate environment setup scripts
        
        ## Instructions
        
        1. Use `/start-session vibe-coder` to begin
        2. Load context from `agentic-development/README.md`
        3. Work through checklist systematically  
        4. Document any issues found and fixes applied
        5. Close this issue when maintenance is complete
        
        ## Success Criteria
        
        - All documentation accurately reflects current structure
        - All load paths and references work correctly
        - No orphaned or redundant files in production
        - System maintenance burden minimized
        EOF
        )" \
          --assignee Tuvens \
          --label "vibe-coder,maintenance,automated"
      env:
        GITHUB_TOKEN: ${{ secrets.TUVENS_DOCS_TOKEN }}