name: Vibe Coder Maintenance Check

on:
  push:
    branches: [ develop ]
    paths: 
      - 'agentic-development/**'
      - '.claude/**'

jobs:
  create-maintenance-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get current date
      id: date
      run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Check if maintenance issue already exists today
      id: check-issue
      run: |
        # Check if an issue with today's date already exists
        ISSUE_COUNT=$(gh issue list --search "[Vibe Coder] System Maintenance Check - ${{ steps.date.outputs.current_date }}" --json number | jq length)
        echo "issue_exists=$ISSUE_COUNT" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create maintenance issue
      if: steps.check-issue.outputs.issue_exists == '0'
      run: |
        gh issue create \
          --title "[Vibe Coder] System Maintenance Check - ${{ steps.date.outputs.current_date }}" \
          --body "$(cat <<'EOF'
        ## Automated System Maintenance Check
        
        **Agent**: Vibe Coder  
        **Trigger**: Push to develop branch affecting agentic-development structure
        **Date**: ${{ steps.date.outputs.current_date }}
        
        ## Tasks to Complete
        
        ### Documentation Accuracy
        - [ ] Verify `agentic-development/README.md` structure matches actual files
        - [ ] Check file counts are accurate (currently 24 production files)
        - [ ] Validate all load paths in `desktop-project-instructions/README.md`
        - [ ] Ensure agent identity files in `.claude/agents/` are current
        
        ### Reference Integrity  
        - [ ] Check for orphaned files without breadcrumb trails
        - [ ] Verify all cross-references between files work
        - [ ] Test `/start-session` command with each agent
        - [ ] Validate setup scripts work correctly
        
        ### System Hygiene
        - [ ] Move any new design docs to `.temp/` directory
        - [ ] Archive outdated workflow files
        - [ ] Update agent terminal prompts if needed
        - [ ] Check for duplicate instructions between Desktop/Code
        
        ### Integration Testing
        - [ ] Test Desktop → Code handoff flow
        - [ ] Verify worktree organization works
        - [ ] Check GitHub issue creation via MCP
        - [ ] Validate environment setup scripts
        
        ## Instructions
        
        1. Use `/start-session vibe-coder` to begin
        2. Load context from `agentic-development/README.md`
        3. Work through checklist systematically  
        4. Document any issues found and fixes applied
        5. Close this issue when maintenance is complete
        
        ## Success Criteria
        
        - All documentation accurately reflects current structure
        - All load paths and references work correctly
        - No orphaned or redundant files in production
        - System maintenance burden minimized
        EOF
        )" \
          --assignee ciarancarroll \
          --label "vibe-coder,maintenance,automated"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}